$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$ReleaseDir = Join-Path $Root "target\x86_64-pc-windows-msvc\release"
$Bridge = Join-Path $ReleaseDir "airwiki-mcp-bridge.exe"
$Desktop = Join-Path $ReleaseDir "airwiki.exe"
$Helper = Join-Path $ReleaseDir "airwiki-windows-firewall-helper.exe"
$Mcpb = Join-Path $Root "target\mcpb\x86_64-pc-windows-msvc\airwiki-claude.mcpb"
$OutDir = Join-Path $Root "target\packages\windows"
$SignedConfig = Join-Path $Root "packaging\windows\Packager.release.generated.toml"
$SigningTemp = Join-Path $Root "target\packages\windows-signing-temp"
$UninstallerReceiptDir = Join-Path $Root "target\windows-uninstaller"
$UninstallerReceipt = Join-Path $UninstallerReceiptDir "airwiki-uninstall.exe"
$LlamaRuntime = Join-Path $Root "resources\llama\windows-x64"
$LlamaPolicy = Join-Path $Root "packaging\llama-windows-build-policy.json"
. (Join-Path $PSScriptRoot "windows-signing.ps1")
. (Join-Path $PSScriptRoot "windows-runtime.ps1")
. (Join-Path $PSScriptRoot "windows-safe-staging.ps1")

$UsePrebuiltMcpb = $env:AIRWIKI_USE_PREBUILT_MCPB -eq "true"
if (-not [string]::IsNullOrWhiteSpace($env:AIRWIKI_USE_PREBUILT_MCPB) -and
    $env:AIRWIKI_USE_PREBUILT_MCPB -ne "true" -and
    $env:AIRWIKI_USE_PREBUILT_MCPB -ne "false") {
    throw "AIRWIKI_USE_PREBUILT_MCPB must be true or false"
}

function Write-SignedPackagerConfig([string] $Destination) {
    $GeneratedMarker = "# Generated by package-signed-windows.ps1; do not edit."
    $TemplatePath = Join-Path $Root "packaging\windows\Packager.toml"
    $Template = [IO.File]::ReadAllText($TemplatePath)
    if ($Template -match '(?m)^\s*signCommand\s*=') {
        throw "tracked Windows packager config must not contain a release signing command"
    }
    $SigningScript = (Resolve-Path (Join-Path $PSScriptRoot "sign-windows-artifact.ps1")).Path.Replace("\", "/")
    if ($SigningScript -match '\s') {
        throw "release workspace path cannot contain whitespace because cargo-packager 0.11.8 tokenizes signCommand"
    }
    $Command = "pwsh.exe -NoProfile -ExecutionPolicy Bypass -File $SigningScript %1"
    $Marker = "[windows]"
    if (([regex]::Matches($Template, '(?m)^\[windows\]\s*$')).Count -ne 1) {
        throw "Windows packager config must contain exactly one [windows] table"
    }
    $Materialized = "$GeneratedMarker`n" + $Template.Replace($Marker, "$Marker`nsignCommand = `"$Command`"")
    if (Test-Path -LiteralPath $Destination) {
        $Existing = [IO.File]::ReadAllText($Destination)
        if (-not $Existing.StartsWith($GeneratedMarker, [StringComparison]::Ordinal)) {
            throw "refusing to overwrite a non-generated release config"
        }
        Remove-AirWikiWindowsStagingPath `
            -Path $Destination `
            -AllowedRoot (Join-Path $Root "packaging\windows") `
            -Label "generated Windows packager configuration"
    }
    [IO.File]::WriteAllText($Destination, $Materialized, [Text.UTF8Encoding]::new($false))
}

$DesktopSigner = Assert-ExpectedWindowsSigner $Desktop
$BridgeSigner = Assert-ExpectedWindowsSigner $Bridge
$HelperSigner = Assert-ExpectedWindowsSigner $Helper
Assert-SameWindowsSigner $DesktopSigner $BridgeSigner "MCP bridge"
Assert-SameWindowsSigner $DesktopSigner $HelperSigner "firewall helper"
Assert-WindowsFirewallHelperManifest $Helper "signed Windows firewall helper"
$null = Get-WindowsLlamaRuntimeManifest $LlamaRuntime $LlamaPolicy
Assert-WindowsDesktopEmbedsLlamaRuntimeHash $Desktop $LlamaRuntime $LlamaPolicy

Push-Location $Root
$PreviousTemp = $env:TEMP
$PreviousTmp = $env:TMP
try {
    Remove-AirWikiWindowsStagingPath `
        -Path $OutDir `
        -AllowedRoot (Join-Path $Root "target") `
        -Label "signed Windows package output"
    Remove-AirWikiWindowsStagingPath `
        -Path $UninstallerReceiptDir `
        -AllowedRoot (Join-Path $Root "target") `
        -Label "Windows uninstaller receipt staging"

    if ($UsePrebuiltMcpb) {
        $ResolvedMcpb = Get-VerifiedWindowsRegularFile $Mcpb "prebuilt Claude MCPB"
        if (-not $ResolvedMcpb.Equals(
            [IO.Path]::GetFullPath($Mcpb),
            [StringComparison]::OrdinalIgnoreCase
        )) {
            throw "prebuilt Claude MCPB resolved outside its fixed artifact path"
        }
    } else {
        & cargo run --locked -p xtask -- packaging verify-windows-uninstaller
        if ($LASTEXITCODE -ne 0) { throw "Windows uninstaller policy validation failed" }

        & cargo run --locked -p xtask -- mcpb build `
            --target x86_64-pc-windows-msvc `
            --bridge $Bridge `
            --output $Mcpb
        if ($LASTEXITCODE -ne 0) { throw "Claude MCPB build failed" }
    }

    Write-SignedPackagerConfig $SignedConfig
    Remove-AirWikiWindowsStagingPath `
        -Path $SigningTemp `
        -AllowedRoot (Join-Path $Root "target") `
        -Label "Windows signing staging"
    New-Item -ItemType Directory -Path $SigningTemp -Force | Out-Null
    # NSIS passes !uninstfinalize a generated .tmp PE. Keeping TEMP inside
    # target lets the closed signing wrapper reject arbitrary filesystem paths.
    $env:TEMP = $SigningTemp
    $env:TMP = $SigningTemp
    & cargo packager --config $SignedConfig
    if ($LASTEXITCODE -ne 0) { throw "cargo-packager failed" }
    $UninstallerSigner = Assert-ExpectedWindowsSigner $UninstallerReceipt
    Assert-SameWindowsSigner $DesktopSigner $UninstallerSigner "generated uninstaller"
} finally {
    $env:TEMP = $PreviousTemp
    $env:TMP = $PreviousTmp
    Remove-AirWikiWindowsStagingPath `
        -Path $SigningTemp `
        -AllowedRoot (Join-Path $Root "target") `
        -Label "Windows signing staging"
    Remove-AirWikiWindowsStagingPath `
        -Path $SignedConfig `
        -AllowedRoot (Join-Path $Root "packaging\windows") `
        -Label "generated Windows packager configuration"
    Pop-Location
}
